local M = {}

M.jackolantern1 = {
	"                           ........",
	"                            ;::;;::;,",
	"                            ;::;;::;;,",
	"                           ;;:::;;::;;,",
	"           .vnmmnv%vnmnv%,.;;;:::;;::;;,  .,vnmnv%vnmnv,",
	"        vnmmmnv%vnmmmnv%vnmmnv%;;;;;;;%nmmmnv%vnmmnv%vnmmnv",
	"      vnmmnv%vnmmmmmnv%vnmmmmmnv%;:;%nmmmmmmnv%vnmmmnv%vnmmmnv",
	"     vnmmnv%vnmmmmmnv%vnmmmmmmmmnv%vnmmmmmmmmnv%vnmmmnv%vnmmmnv",
	"    vnmmnv%vnmmmmmnv%vnmmmmmmmmnv%vnmmmmmmmmmmnv%vnmmmnv%vnmmmnv",
	"   vnmmnv%vnmmmmmnv%vnmm;mmmmmmnv%vnmmmmmmmm;mmnv%vnmmmnv%vnmmmnv,",
	"  vnmmnv%vnmmmmmnv%vnmm;' mmmmmnv%vnmmmmmmm;' mmnv%vnmmmnv%vnmmmnv",
	"  vnmmnv%vnmmmmmnv%vn;;    mmmmnv%vnmmmmmm;;    nv%vnmmmmnv%vnmmmnv",
	" vnmmnv%vnmmmmmmnv%v;;      mmmnv%vnmmmmm;;      v%vnmmmmmnv%vnmmmnv",
	" vnmmnv%vnmmmmmmnv%vnmmmmmmmmm;;       mmmmmmmmmnv%vnmmmmmmnv%vnmmmnv",
	" vnmmnv%vnmmmmmmnv%vnmmmmmmmmmm;;     mmmmmmmmmmnv%vnmmmmmmnv%vnmmmnv",
	" vnmmnv%vnmmmmm nv%vnmmmmmmmmmmnv;, mmmmmmmmmmmmnv%vn;mmmmmnv%vnmmmnv",
	" vnmmnv%vnmmmmm  nv%vnmmmmmmmmmnv%;nmmmmmmmmmmmnv%vn; mmmmmnv%vnmmmnv",
	" `vnmmnv%vnmmmm,  v%vnmmmmmmmmmmnv%vnmmmmmmmmmmnv%v;  mmmmnv%vnnmmnv'",
	"  vnmmnv%vnmmmm;,   %vnmmmmmmmmmnv%vnmmmmmmmmmnv%;'   mmmnv%vnmmmmnv",
	"   vnmmnv%vnmmmm;;,   nmmm;'              mmmm;;'    mmmnv%vnmmmmnv'",
	"   `vnmmnv%vnmmmmm;;,.         mmnv%v;,            mmmmnv%vnmmmmnv'",
	"    `vnmmnv%vnmmmmmmnv%vnmmmmmmmmnv%vnmmmmmmnv%vnmmmmmnv%vnmmmmnv'",
	"      `vnmvn%vnmmmmmmnv%vnmmmmmmmnv%vnmmmmmnv%vnmmmmmnv%vnmmmnv'",
	"          `vn%vnmmmmmmn%:%vnmnmmmmnv%vnmmmnv%:%vnmmnv%vnmnv'",
}

M.jackolantern2 = {
	[[                            Jgy__]],
	[[                        jWW  `""9Wf]],
	[[                      _#WWW     IW]],
	[[                     jWWWWW     IW]],
	[[             __,yyyyyWWWWW     IWyyyy___]],
	[[        _jyWWP"^``"`.C"9*,J _.mqD:^^"WWWWWWQg__]],
	[[      jgW"^.C/"    .C'     I    `D.     'D._"WQg_]],
	[[    jWP` .C"       C'      I     `D._     `D._ "Qg_]],
	[[  jQP`  .C    ,d^^b._      I      _.d^^b.   `D._ "Qg]],
	[[ jQ^  .C"   /`   .+" \     I     / "+.   `\   `D.  XQ]],
	[[jQ'  .C'   |`  ."    )    _I    (     ".  |    `D.  4#]],
	[[Qf  .C     (   (    /    / /\    \     )  )     `D.  Qg]],
	[[W   C'      \__\_.+'    / /  \    `+._/__/       `D  jQ]],
	[[f   C         C        /_/    \         D         D   Qk]],
	[[f   C      _  C        \_\____/         D  _      D   QF]],
	[[L   C      \`+.__     _______     ______.+'/      D   QF]],
	[[&   C.      \   \|    ||     |    ||      /       D   Qf]],
	[[Q   `C.      \   |____|/     |____|/__   /      .D'   jW]],
	[[TQ   `C.      \._   `+.__________/___/|_/      .D'   jQ`]],
	[[ 9Q   `C.      C.`+._           |   |/.D'     .D'   jQ']],
	[[  "Qg  `C.     `C.   `"+-------'   ' .D'     .D'   pW`]],
	[[   ^WQy `C.     `C.        I        .D'    _.D' yW"]],
	[[     ^9Qy_`C.    `C.       I       .D'   _.D jgW"]],
	[[        `9WQgC.__ `C.      I      .D'  _.Dp@@"`]],
	[[            `""9WQQggyyyyyygyyyyyQggQWQH""]],
}

M.jackolanterns = {
	[[                                        _]],
	[[                      /\              )\]],
	[[        _           __)_)__        .'`--`'.]],
	[[        )\_      .-'._'-'_.'-.    /  ^  ^  \]],
	[[     .'`---`'. .'.' /o\'/o\ '.'.  \ \/\/\/ /]],
	[[    /  <> <>  \ : ._:  0  :_. : \  '------'       _J_]],
	[[    |    A    |:   \\/\_/\//   : |     _/)_    .'`---`'.]],
	[[    \  <\_/>  / :  :\/\_/\/:  : /   .'`----`'./.'0\ 0\  \]],
	[[   _?_._`"`_.'`'-:__:__:__:__:-'   /.'<\   /> \:   o    |]],
	[[.'`---`'.``  _/(              /\   |:,___A___,|' V===V  /]],
	[[.'a . a  \.'`---`'.        __(_(__ \' \_____/ /'._____.']],
	[[:  ___   /.'/\ /\  \    .-'._'-'_.'-:.______.' _?_]],
	[['  \_/   |:   ^    |  .'.' (o\'/o) '.'.     .'`"""`'.]],
	[['._____.'\' 'vvv'  / / :_/_:  A  :_\_: \   /   ^.^   \]],
	[[          '.__.__.' | :   \'=...='/   : |  \  `===`  /]],
	[[                     \ :  :'.___.':  : /    `-------`]],
	[[                      '-:__:__:__:__:-']],
}

M.castle = {
	[[#  #   #   #### #### #   #]],
	[[####  ###  # ## # ##  ###]],
	[[#  # # # # #    #      #]],
	[[]],
	[[       #  #   #   #   #    ##  #     # #### #### #  ##]],
	[[       ####  ###  #   #   #  #  # # #  #--  #--  # # #]],
	[[       #  # #   # ### ###  ##    ###   #### #### ##  #]],
	[[]],
	[[                           .-----.]],
	[[                         .'       `.]],
	[[                        :      ^v^  :]],
	[[                        :           :]],
	[[                        '           ']],
	[[         |~        www   `.       .']],
	[[        /.\       /#^^\_   `-/\--']],
	[[       /#  \     /#%    \   /# \]],
	[[      /#%   \   /#%______\ /#%__\]],
	[[     /#%     \   |= I I ||  |- |]],
	[[     ~~|~~~|~~   |_=_-__|'  |[]|]],
	[[       |[] |_______\__|/_ _ |= |`.]],
	[[^V^    |-  /= __   __    /-\|= | :;]],
	[[       |= /- /\/  /\/   /=- \.-' :;]],
	[[       | /_.=========._/_.-._\  .:']],
	[[       |= |-.'.- .'.- |  /|\ |.:']],
	[[       \  |=|:|= |:| =| |~|~||'|]],
	[[        |~|-|:| -|:|  |-|~|~||=|      ^V^]],
	[[        |=|=|:|- |:|- | |~|~|| |]],
	[[        | |-_~__=_~__=|_^^^^^|/___]],
	[[        |-(=-=-=-=-=-(|=====/=_-=/\]],
	[[        | |=_-= _=- _=| -_=/=_-_/__\]],
	[[        | |- _ =_-  _-|=_- |]#| I II]],
	[[        |=|_/ \_-_= - |- = |]#| I II]],
	[[        | /  _/ \. -_=| =__|]!!!I_II!!]],
	[[       _|/-'/  ` \_/ \|/' _ ^^^^`.==_^.]],
	[[     _/  _/`-./`-; `-.\_ / \_'\`. `. ===`.]],
	[[    / .-'  __/_   `.   _/.' .-' `-. ; ====;\]],
	[[   /.    ./    \ `. \ / -  /  .-'.' ====='  >]],
	[[  /  \  /  .-' `--.  / .' /  `-.' ======.' /]],
}

return M
